### ISSUE TITLE
No cmp LSP completion with TSX

### ISSUE THREAD

**Issue by yngwi** [pmizio/typescript-tools.nvim#117]
Hi, I'm having problems in getting the LSP completion to work in cmp and *.tsx files. Everything works fine for normal typescript files as far as I can tell. Is there something specific to be done to make tsx work? Other language servers need the extended capabilities that cmp provides, could this maybe be the reason? Thank you!

**Comment by pmizio** [comment]
@yngwi IDK, it should work out of the box, I use pretty standard lsp config contained in [lsp-zero](https://github.com/VonHeikemen/lsp-zero.nvim). I suppose it can be connected with capabilities but on other hand its weird it works for `.ts` but not `.tsx`. There is no additional step to enable tsx, because It have first class support in tsserver.
I checked it latest master:

https://github.com/pmizio/typescript-tools.nvim/assets/4346598/0f42f24f-b714-4cd4-8fd5-7b529a8ceb5c

What you can do:
- To confirm it is something in your config you can try some community distribution(I know it works in lunarvim)
- You can try to create minimal config which reproduce your issue.

**Comment by yngwi** [comment]
Thank you for confirming that it works on your end, it must be something else then. I'll close this issue and investigate.

**Comment by turkus** [comment]
@yngwi did you resolve that problem? I had the same issue even with basic config from README.

**Comment by yngwi** [comment]
> @yngwi did you resolve that problem? I had the same issue even with basic config from README.

Unfortunately not, I only use the language server itself nowadays, no "helper" plugins.

**Comment by turkus** [comment]
@yngwi see https://github.com/pmizio/typescript-tools.nvim/issues/319#issuecomment-2514954509 cause I think it's related.
