### ISSUE TITLE
Freeze for a while when open a ts file and Completion is slow too.

### ISSUE THREAD

**Issue by BingCoke** [pmizio/typescript-tools.nvim#119]
I use the same config with two device. But one device will meet the problem i said , the other is fine.
All of them system is arch.
Has anyone had the same problem? I don't know what's wrong there,

**Comment by BingCoke** [comment]
here is my config
```lua
	require("typescript-tools").setup({
		on_attach = function(cli, buf)
			on_attach(cli, buf)
		end,
		capabilities = default_capabilities,
	})
```

**Comment by pmizio** [comment]
I see multiple reasons why it can happen. You may check this on both devices and compare:
- Neovim version
- Typescript version 
- Node version
- Even some system or device related stuff

Idk really, but probably it isn't on our side because your config works fine on different hardware on same system so... probably problem is in other system/device.
