### ISSUE TITLE
Root Directory resolves incorrectly if parent directory also has a `tsconfig.json`?

### ISSUE THREAD

**Issue by monsonjeremy** [pmizio/typescript-tools.nvim#121]
I have a project that looks like so:
```
| - tsconfig.json
| - server/
     | - tsconfig.json
```

When I run `:LspInfo` and inspect the root directory that `typescript-tools` is using, it seems to resolve one directory up. In this case the `tsconfig` at the top is used as an `extends` for other parts of the project, but not the server directory. It should use the current working directory in the case that both the current working directory and the parent have these files?

Both have `package.json` as well, so maybe the fact that the parent has a `.git/` folder makes the heuristic prefer that?

**Comment by pmizio** [comment]
@monsonjeremy Today I don't have time to look into it but tomorrow I check this.

But I want to gather more information to reproduce this. Project look like this:
```
| - tsconfig.json(this is base)
| - server/
     | - tsconfig.json(this import top level config)
```

And typescript is installed only in server subdirectory, project root or in both places?

**Comment by pmizio** [comment]
@monsonjeremy Sorry for checking this that late but I tried it and it for me it works ok.
Only case when I get parent directory instead server one is: when I open some server file and nvim was started at root of project not in server subdir. But it working like that by design because `root_dir` resolution walk up into directory tree(from children to parent).

So you never get server as rootdir when you open it from project root.

Let me know if it is your case. If it is I suggest:
```
cd .../server
nvim
```

If it is some other case please give me some more context or minimal reproduction repo would be awesome.

**Comment by pmizio** [comment]
I cannot reproduce this. Closing for now if you want to provide more context feel free to reopen.
