### ISSUE TITLE
Syntax highlight changes when loading the LSP

### ISSUE THREAD

**Issue by guillenotfound** [pmizio/typescript-tools.nvim#210]
LSP stopped:
<img width="533" alt="image" src="https://github.com/pmizio/typescript-tools.nvim/assets/5492960/f7d4970a-d463-4294-a333-d7a915b5bf8e">

LSP running:
<img width="524" alt="image" src="https://github.com/pmizio/typescript-tools.nvim/assets/5492960/b965e489-3125-4105-b8e3-4176403e36ac">

Is there a way to disable typescript-tools syntax highlighting? I guess it has something to do `documentHighlight` but I'm not sure how to disable it.

**Comment by pmizio** [comment]
Hello @guillenotfound this is semantic token feature from lsp. Probably your color scheme doesn't have some color definitions this feature requires.
But if you want disable it you may do it like this:
```lua
require("typescript-tools").setup {
  -- ... rest of your config
  on_attach = function(client, bufnr)
    client.server_capabilities.semanticTokensProvider = nil -- this line do the trick

    -- ... rest of your on_attach function
  end,
}
```

**Comment by chnn** [comment]
Hm I tried disabling it like suggested, but I'm still seeing document highlights as soon as typescript-toos.nvim loads.

https://github.com/pmizio/typescript-tools.nvim/assets/638955/860e4a2c-5be1-47ae-b771-f46c93ae5b80

Relevant config:

```lua
require("typescript-tools").setup({
  separate_diagnostic_server = false,
  on_attach = function(client, bufnr)
    -- Use built-in gq formatexpr which works better for comments
    vim.o.formatexpr = ""

    -- Disable highlighting from tsserver
    client.server_capabilities.semanticTokensProvider = nil
  end,
})
```

[Full config](https://github.com/chnn/dotfiles/blob/259f4d320073ff0c3f345e62350cfa693e01040a/.config/nvim/init.lua)

I'm looking to disable the highlighting from tsserver since it is noticeably slower than both Treesitter or the regex-based highlights system for a large codebase.

**Comment by pmizio** [comment]
@chnn I can be connected with https://github.com/pmizio/typescript-tools.nvim/issues/219#issuecomment-1890337658 I just merged fix can you retest?
