### ISSUE TITLE
Add instructions on how to execute refactoring actions

### ISSUE THREAD

**Issue by stefanwatt** [pmizio/typescript-tools.nvim#73]
There's nothing about this in the help file, if I'm not mistaking.
I have no clue how to add a keymap for "extract to function" etc.

**Comment by pmizio** [comment]
Extract to function and so on are just codeactions you need to bind them also in visual mode then invoking this binding will give you option to perform refactor. I have some like this in my on_attach
```lua
vim.keymap.set({ "n", "x", "v" }, "<leader>ca", vim.lsp.buf.code_action, { buffer = bufnr })
```

**Comment by gwenyambira** [comment]
I was having the same issue as you @gipo355. In my case, it was because the key binding for code actions was defined elsewhere, and not within the `on_attach` function of `require("typescript-tools").setup` . Once I had set the keymap in that function I was able to get the same visual mode refactor actions shown in the GIF.
```lua
require("typescript-tools").setup({
    on_attach = function(client, bufnr)
        vim.keymap.set({ "n", "v" }, "<leader>ca", vim.lsp.buf.code_action, { buffer = bufnr })
    end,
})
```
