### ISSUE TITLE
:LspRestart does not restart typescript-tools

### ISSUE THREAD

**Issue by patlux** [pmizio/typescript-tools.nvim#97]
Hey all,

I'm using LunarVim and now using this plugin for the `tsserver`-lsp. I have the issue, when running `:LspRestart` to restart all lsp-servers that `typescript-tools` does not restart like the others.

Please ask for anything you need to debug the issue. I'm just a vim user without any experience in developing for vim or debugging.

Thank you all!

**Comment by pmizio** [comment]
For now as workaround you may try to do `:LspStop` and then `:LspStart`. I'm on vacation now so I check this out after monaday.

**Comment by pmizio** [comment]
@patlux  Ok, I checked it out with below minimal configuration:
```lua
vim.list_extend(lvim.lsp.automatic_configuration.skipped_servers, { "tsserver" })
lvim.plugins = {
  {
    "pmizio/typescript-tools.nvim",
    dependencies = { "nvim-lua/plenary.nvim", "neovim/nvim-lspconfig" },
    opts = {},
  },
}
```

Note I disabled `tsserver` it can cause conflicts. And this configuration restarts server just fine. With one exception, maybe it's your case: Server cannot be reseted right after it starts, because it still indexing project and until indexing ends server don't respond to user commands(kill server is command). This is somehow bugish and probably we can check state of indexing and send os kill instead of user command to end process.

But for now you can check this minimal config I wrote before and tell me if it is ok. One thing if you don't have `tsserver` disabled and you do that, then you need to run `:LvimCacheReset` command after doing that to 'flush' changes[(lvim docs)](https://www.lunarvim.org/docs/configuration/language-features/language-servers#changing-the-default-server). If it is ok, then try to provide minimal config of yours where problem starts to show up.
Or maybe this is case I described before and we need to fix that.

**Comment by pmizio** [comment]
Nice, thanks for reply. Closing.
